/*
 * ZdCLSync
 *
 * This server is used to simplify keeping instances of the Zendesk Call Logger application up to date with the configured assets and site contacts. It also acts as an online backup of the calls logged by users of the app.  The Zendesk Call Logger application can be found [here](https://gitea.rantorium.com/MTS_ISC/zdcl).
 *
 * API version: 0.0.2
 * Contact: troy.campbell@global.komatsu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package service

type Asset struct {
	Id   int64  `json:"id,omitempty"`
	Name string `json:"name"`
	Org  int64  `json:"org"`
	Tag  string `json:"tag"`
}
