/*
 * ZdCLSync
 *
 * This server is used to simplify keeping instances of the Zendesk Call Logger application up to date with the configured assets and site contacts. It also acts as an online backup of the calls logged by users of the app.  The Zendesk Call Logger application can be found [here](https://gitea.rantorium.com/MTS_ISC/zdcl).
 *
 * API version: 0.0.2
 * Contact: troy.campbell@global.komatsu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package service

type Caller struct {
	// identifier from zendesk
	Id int64 `json:"id"`
	// caller's name
	Name string `json:"name"`
	// caller's organisation
	Organisation string `json:"organisation"`
	// caller's email address
	Email string `json:"email"`
	// caller's phone number
	Phone string `json:"phone"`
	// contextual notes about the caller
	Notes string `json:"notes,omitempty"`
}
