// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTicket(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateTicket'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetAllCallers() {
  return window['go']['main']['App']['GetAllCallers']();
}

export function GetCallersByOrg(arg1) {
  return window['go']['main']['App']['GetCallersByOrg'](arg1);
}

export function GetOrgNames() {
  return window['go']['main']['App']['GetOrgNames']();
}

export function SearchContactByName(arg1) {
  return window['go']['main']['App']['SearchContactByName'](arg1);
}

export function SearchContactByOrg(arg1) {
  return window['go']['main']['App']['SearchContactByOrg'](arg1);
}

export function StoreAgentCredentials(arg1, arg2) {
  return window['go']['main']['App']['StoreAgentCredentials'](arg1, arg2);
}
