// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchContactByName(arg1:string):Promise<string>;

export function SearchContactByOrg(arg1:string):Promise<string>;
