// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchContactByName(arg1) {
  return window['go']['main']['App']['SearchContactByName'](arg1);
}

export function SearchContactByOrg(arg1) {
  return window['go']['main']['App']['SearchContactByOrg'](arg1);
}
