// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTicket(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function GetAllCallers():Promise<Array<string>>;

export function GetCallersByOrg(arg1:string):Promise<Array<string>>;

export function GetOrgNames():Promise<Array<string>>;

export function SearchContactByName(arg1:string):Promise<string>;

export function SearchContactByOrg(arg1:string):Promise<string>;

export function StoreAgentCredentials(arg1:string,arg2:string):Promise<string>;
